---
# network
host: '0.0.0.0'
port: 5566

# map
# map_file: '/home/jehon/Development/til-final/data/maps/map_empty_1cm.png'
# map_file: f'{root_dir}/data/maps/test_5cm.png'
map_file: 'C:\Users\intern\Downloads\til-final-2022.1.1-best\til-final-2022.1.1-lower\data\maps\test_5cm.png'
map_scale: 0.05

# display
robot_radius: 6

# simulation
start_pose:
  x: 3.0
  y: 3.0
  z: -90.0
use_noisy_pose: off
robot_phy_length: 0.32
pos_noise_stddev: 0.05

# localization proxy/localization server(actual)
proxy_real_robot: off
proxy_host: 'localhost'
proxy_port: 5567

# logging
log_level: 'info'

# clues
clues:
  - clue_id: 1
    trigger:
      x: 3.0
      y: 3.0
      r: 0.5
    location:
      x: 3.0
      y: 1.0
    audio_file: 'C:\Users\intern\Downloads\til-final-2022.1.1-best\til-final-2022.1.1-lower\data\audio\SM4_F48_A0100.wav'
  - clue_id: 2
    trigger:
      x: 3.0
      y: 1.0
      r: 0.5
    location:
      x: 0.7
      y: 1.0
    audio_file: 'C:\Users\intern\Downloads\til-final-2022.1.1-best\til-final-2022.1.1-lower\data\audio\SM4_F48_A0100.wav'
  - clue_id: 3
    trigger:
      x: 3.0
      y: 4.5
      r: 0.5
    location:
      x: 1.5
      y: 2.5
    audio_file: 'C:\Users\intern\Downloads\til-final-2022.1.1-best\til-final-2022.1.1-lower\data\audio\SM4_F48_A0100.wav'
  - clue_id: 4
    trigger:
      x: 2.5
      y: 3.5
      r: 0.6
    location:
      x: 1.5
      y: 3.5
    audio_file: 'C:\Users\intern\Downloads\til-final-2022.1.1-best\til-final-2022.1.1-lower\data\audio\SM4_F48_A0100.wav'
# targets
targets:
  - target_id: 1
    trigger:
      x: 3.0
      y: 2.7
      r: 1.0
    image_file: 'C:\Users\intern\Downloads\til-final-2022.1.1-best\til-final-2022.1.1-lower\data\imgs\fallen_person.jpeg'
  - target_id: 2
    trigger:
      x: 2.2
      y: 0.8
      r: 1.0
    image_file: 'C:\Users\intern\Downloads\til-final-2022.1.1-best\til-final-2022.1.1-lower\data\imgs\IDH202001.png'
  - target_id: 3
    trigger:
      x: 0.5
      y: 1.5
      r: 1.0
    image_file: 'C:\Users\intern\Downloads\til-final-2022.1.1-best\til-final-2022.1.1-lower\data\imgs\OLH413036.png'
  - target_id: 4
    trigger:
      x: 0.5
      y: 2.5
      r: 1.0
    image_file: 'C:\Users\intern\Downloads\til-final-2022.1.1-best\til-final-2022.1.1-lower\data\imgs\OLM532004.png'
  - target_id: 5
    trigger:
      x: 0.5
      y: 4.5
      r: 1.0
    image_file: 'C:\Users\intern\Downloads\til-final-2022.1.1-best\til-final-2022.1.1-lower\data\imgs\photo.jpg'